### ISSUE TITLE
Use some code style/linting

### ISSUE THREAD

**Issue by xdumaine** [latentflip/websocket-debug#3]
@latentflip thoughts? I'm partial to semistandard, and would like to use es6 where supported.

**Comment by latentflip** [comment]
Yup and yup. Though don't feel obliged to refactor my work! This was definitely a "just make it work well enough" 0.1 hack together!

**Comment by latentflip** [comment]
Okay, made a start on this. Tried to tidy things up a little, added semistandard + git-validate.
