### ISSUE TITLE
Pretty printing xml is buggy

### ISSUE THREAD

**Issue by latentflip** [latentflip/websocket-debug#4]
So, I guess chrome treats arbitrary xml weirdly when setting it as `innerHTML`, which is the hack we were using for pretty-printing xml:

![2016-05-09 15-07-46](https://cloud.githubusercontent.com/assets/78225/15115637/e6bdb7e0-15f7-11e6-8cad-9e8240fad040.png)

Note how it trips up over self-closing elements that it doesn't think should be self-closing.

**Comment by xdumaine** [comment]
Check out `DOMParser`

![image](https://cloud.githubusercontent.com/assets/833911/15116684/4d648620-15d2-11e6-8d56-3bf656db0345.png)

``` javascript
const parser = new DOMParser();
parser.parseFromString('<foo><bar/><baz/><bux/></foo>', 'text/xml')
```

**Comment by latentflip** [comment]
You legend, thanks!
